name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.12.1
      - scikit-learn==1.3.2
      - pandas==2.1.4
      - numpy==1.26.4
      - matplotlib
      - seaborn
